add indonesian translation
semver/semver.org pull request #167
Opened 2017-03-22 09:51 UTC by adityapurwa

Add indonesian transation, Bahasa Indonesia.

2017-03-22 18:19 UTC, Haacked commented
Hi! Could you find someone to review this translation?

2017-03-22 18:20 UTC, Haacked commented
Actually, there's already an Indonesian translation: https://github.com/mojombo/semver.org/pull/166

Would you mind closing this and reviewing that one?

2017-03-23 02:33 UTC, adityapurwa commented
Closed to review other translation.

2017-03-25 15:31 UTC, adityapurwa commented
Reopen because #166 is closed and the user deleted his account.

2017-04-01 11:58 UTC, adityapurwa commented
@Haacked any info for this pull request??

2017-04-01 23:08 UTC, Haacked commented
@adityapurwa can you find another person to review the translation?

2017-04-02 09:36 UTC, cwibowo commented
I'll do it. :)

2017-04-02 10:24 UTC, cwibowo requested changes
Great work, @adityapurwa !
I do have several suggestion that you may/may not use. Please also implement the changes in the other file (2.0.0 md)

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +1. Tambah angka versi MAJOR jika membuat perubahan yang merubah API.
This is the most important part of the document, imho. We need to make it really clear. I would change this to:
the translation for incompatible is tidak cocok dengan versi sebelumnya
> ....membuat perubahan API yang tidak lagi cocok dengan versi sebelumnya

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Jika spesifikasi kebutuhan sistem terlalu ketat, bisa jadi sistem kita tidak bisa dikembangkan
spesifikasi dependensi instead of spesifikasi kebutuhan. Dependensi is a valid word in Indonesia (check KBBI)

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +lagi. Jika spesifikasi kebutuhan sistem terlalu luas, semakin sulit untuk mengatur versi mana
Jika spesifikasi dependensi terlalu bebas (loosely)

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +tersebut. Pembetulan bug menambah angka patch, penambahan fitur menambah angka minor, perubahan
menaikkan angka patch instead of menambah. menaikkan angka minor instead of menambah angka minor

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +yang membuat versi lama tidak bisa digunakan menambah angka major.
menaikkan angka major

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Standar ini bernama "Versi Semantik", dengan standar ini, setiap orang yang melihat
in Semantic Versioning, Versioning is a gerund, a verb form which functions as a noun.
in Indonesians gerund usually exists in form of pe-an. so Pemberian Versi Semantik is better than Versi Semantik.
(untuk judul tetap gunakan Versi Semantik supaya mudah dalam penyingkatan)

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +2. Versi HARUS ditulis dalam bentuk X.Y.Z, dengan X, Y, Z angka bulat positif, dan TIDAK
in formal Indonesian bilangan bulat positif instead of angka bulat positif.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +3. Setelah versi dirilis, isi dari versi tersebut TIDAK BOLEH dirubah. Setiap perubahan harus
HARUS instead of harus

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +4. Versi major 0 (0.y.z) adalah untuk pengembangan, dan bisa terjadi banyak perubahan. API publik
pengembangan awal <= initial development

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +yang ditandai usang, bisa dirubah bersama dengan versi patch, jika minor ditambahkan, maka versi patch harus dikembalikan ke angka 0.
yang sudah usang. Versi ini BISA dinaikkan jika ada tambahan fungsionalitas substansial atau terjadi peningkatan. Versi ini BISA diubah bersama dengan versi patch. Versi Patch HARUS dikembalikan ke angka 0 jika versi minor dinaikkan.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +8. Versi major X (X.y.z | X > 0) HARUS ditambah jika ada perubahan yang membuat versi baru
HARUS dinaikkan

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +digunakan di versi lama, bisa dirubah bersama dengan versi patch dan minor, jika major ditambahkan, maka versi minor dan patch harus dikembalikan ke angka 0.
diubah.
jika versi major dinaikkan/ditingkatkan

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +10. Data tambahan BISA ditulis setelah versi sebelum rilis didahului dengan tanda tambah
I am not sure if there's a translation for Build Metadata, but it's not Data Tambahan

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Kenapa Menggunakan Versi Semantik
Pemberian Versi Semantik :)

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Contohnya adalah ada sebuah modul dengan nama "Truk". Modul tersebut butuh dengan modul lain dengan nama "Tangga". Ketika "Truk" dibuat, versi "Tangga" masih dalam 3.1.0. Karena "Truk" menggunakan ve
Contoh sederhana berikut ini menunjukkan manfaat Pemberian Versi Semantik untuk menghilangkan "dependency hell". Misalkan ada sebuah modul bernama "MobilPemadamKebakaran". Modul "MobilPemadamKebakaran" membutuhkan modul lain bernama "Tangga". Pada waktu "MobilPemadamKebakaran" dibuat, "Tangga" memiliki versi 3.1.0. Dengan menggunakan Pemberian Versi Semantik, "MobilPemadamKebakaran" bisa dengan yakin menggunakan modul "Tangga" selama modul tersebut mempunyai versi antara 3.1.0 sampai dengan sebelum versi 4.0.0.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Versi Semantik adalah standar, dan mungkin bisa diikuti dan tidak diikuti, dan tugas dari standar hanyalah untuk membantu supaya pemberian versi bisa lebih jelas.
Pemberian Versi Semantik adalah aturan baku yang bisa diikuti dan bisa saja tidak.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Jika standar ini terdengar bagus, kalian bisa mulai menggunakan standar Versi Semantik dan mengikuti aturannya. Tautkan ke website ini supaya orang lain bisa menggunakan standar Versi Semantik juga.
Jika menurut kalian aturan baku ini bagus, kalian bisa mulai menggunakan pemberian versi semantik. Tautkan situs ini dalam README kalian supaya orang lain bisa tahu mengenai aturan ini dan mulai menggunakannya juga.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Ketika sistem yang dikembangkan sudah stabil dan bisa digunakan di sistem produktif, kalian bisa
Ketika sistem yang dikembangkan sudah stabil dan digunakan dalam lingkungan produksi.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Langsung rubah perubahan tersebut dan kembalikan supaya masih bisa digunakan versi lama dan tambahkan versi minor.
Langsung ganti perubahan tersebut dan kembalikan supaya masih bisa digunakan versi lama dan naikkan versi minor.

2017-04-02 10:24 UTC, cwibowo commented on lang/id/index.md
> +Sudah tanggung jawab bagi pengembang untuk memastikan sistemnya bisa digunakan dengan baik dan mudah. Versi Semantik hanya memandu orang untuk bisa saling seragam dan bisa bekerja sama dengan baik.
Sudah tanggung jawab pengembang untuk memastikan sistemnya bisa digunakan dengan baik dan mudah. Pemberian Versi Semantik hanya memandu orang untuk konsisten dan bisa bekerja sama dengan baik.

2017-04-02 12:08 UTC, adityapurwa commented
@cwibowo Thanks for the review, I will try to do some corrections and changes you suggested.

2017-04-20 08:01 UTC, adityapurwa commented
@Haacked a reviewed version has been committed.

2017-04-20 08:53 UTC, cwibowocoolblue approved these changes
-

2017-04-20 08:56 UTC, cwibowo approved these changes
sorry, wrong account :)
Nice work, @adityapurwa
Looks good to me, @Haacked

2017-04-20 21:00 UTC, Haacked commented
Excellent! Thanks!

2017-04-20 21:00 UTC, merged