Improved Polish translation
semver/semver.org pull request #171
Opened 2017-06-22 22:40 UTC by m-aciek

Style, punctuation

2017-10-04 21:15 UTC, Haacked commented
Thanks! Sorry for the late reply. Do you know other native Polish speakers who can double check your work here? That would be helpful to me as I don't speak Polish.

2017-10-05 06:49 UTC, m-aciek commented
Sure, I will try to find someone to help and review those changes.

2017-10-05 10:53 UTC, yisonPylkita requested changes
Hi
I am a native polish speaker and colleague of @m-aciek.

Everything beside marked lines seems to be fine.

2017-10-05 10:53 UTC, yisonPylkita commented on lang/pl/index.md
> +1. wersję PATCH, gdy naprawiasz błąd w sposób kompatybilny z poprzednimi wersjami.
It should be `gdy naprawiasz błąd nie zrywając kompatybilności z poprzednimi wersjami.`

2017-10-05 10:53 UTC, yisonPylkita commented on lang/pl/index.md
> +System ten został nazwany przeze mnie „wersjonowaniem semantycznym”. W systemie tym numery wersji i sposób, w jaki zostają zmienione, wskazują na tworzący je kod oraz na to, co zostało zmodyfikowane
These commas are invalid here.

2017-10-09 21:21 UTC, m-aciek commented
During last few days I reworked the translation, making new translation for some parts of the document. I've split the lines to have width of 80, like in original document.

@yisonPylkita, could you review new changes and leave your feedback here again?

2017-10-09 21:25 UTC, yisonPylkita commented
@m-aciek  Yes, of course. I will check changes tomorrow.

2017-10-09 21:28 UTC, yisonPylkita commented
There seems to be a lot of changes. I will check them tomorrow.

2017-10-09 21:29 UTC, m-aciek commented
Sure, thanks!

2017-10-13 19:39 UTC, yisonPylkita approved these changes
I have no objections to this change.  Most of the Readme was re-written and now reading it feels way better.

Great job @m-aciek

2017-10-16 18:27 UTC, Haacked commented
Thanks!

2017-10-16 18:27 UTC, merged