Add Georgian (ka) translation
semver/semver.org pull request #177
Opened 2017-10-11 15:22 UTC by akalongman

This PR adds Georgian (ka) translation.

As a reviewer, I want invite @torniker

2017-10-11 17:42 UTC, torniker requested changes
კარგი ხარ! ეს ორი შეცდომა გაასწორე და დავაეფრუვებ.

2017-10-11 17:42 UTC, torniker commented on lang/ka/index.md
> +სისტემაში სადაც ბევრი დამოკიდებულებებია, ახალი ვერსიის გამოშვება შეიძლება
ბევრი დამოკიდებულებაა

2017-10-11 17:42 UTC, torniker commented on lang/ka/index.md
> +მე ამას ვუწოდებ "სემანტიკურ ვერსიონირებას" (Semantic Versioning). ამ სქემის მიხედვით
მე ზედმეტია. ის მგონი ჯობია ამას ეწოდება ანუ ზოგადი ფორმით რომ ჩაიწეროს.

2017-10-11 17:51 UTC, torniker requested changes
კარგი ხარ! ეს ორი შეცდომა გაასწორე და დავაეფრუვებ.

2017-10-12 08:58 UTC, akalongman commented on lang/ka/index.md
> +სისტემაში სადაც ბევრი დამოკიდებულებებია, ახალი ვერსიის გამოშვება შეიძლება
ეს გავასწორე :+1:

2017-10-12 09:02 UTC, akalongman commented on lang/ka/index.md
> +მე ამას ვუწოდებ "სემანტიკურ ვერსიონირებას" (Semantic Versioning). ამ სქემის მიხედვით
კი ვიფიქრე მეც, მაგრამ ყველგან ეგრე სიტყვასიტყვითაა ნათარგმნი და მეც ესე ვთარგმნე. ალბათ უნდა ხაზი გაუსვას, რომ ამას ის უწოდებს "სემანტიკურ ვერსიონირებას", ანუ მისი შემოღებული ტერმინია.

2017-10-12 09:13 UTC, torniker approved these changes

2017-10-31 08:00 UTC, akalongman commented
@Haacked ping

2017-10-31 21:00 UTC, Haacked commented
Thanks!

2017-10-31 21:00 UTC, merged