Translation document to Vietnamese
semver/semver.org pull request #228
Opened 2019-07-23 06:46 UTC by M1nhNV

2020-06-09 20:29 UTC, alexandrtovmach commented
@M1nhNV Thanks for contribution. Do you know any native speaker who can review these changes?

2020-06-17 06:07 UTC, tolyteo12345 approved these changes
Look good to me!

2020-06-17 06:11 UTC, Quynh-Nguyen approved these changes
LGTM!

2020-06-17 06:15 UTC, M1nhNV commented
@alexandrtovmach Native speaker maybe @Quynh-Nguyen or @anhtuan3996

2020-06-17 06:59 UTC, alexandrtovmach approved these changes

2020-06-17 07:00 UTC, alexandrtovmach commented
/check

2020-06-17 07:02 UTC, merged

2020-06-17 07:11 UTC, reishou requested changes

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +1. Số phiên bản MAJOR khi bạn có các thay đổi lớn về API
`MAJOR version` - I think it should be original

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +2. Số phiên bản MINOR khi bạn thêm chức năng tương thích ngược với phiên bản trước
`MINOR version` - I think it should be original

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +3. Số phiên bản PATCH khi bạn làm một bản vá lỗi tương thích ngược với phiên bản trước
`PATCH version` - I think it should be original

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +Bổ sung các nhãn cho tiền phát hành và xây dựng các siêu dữ liệu sẵn sàng như là một tiện ích mở rộng theo định dạng MAJOR.MINOR.PATCH
`metadata`, `pre-release ` should be original

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +Trong các hệ thống có nhiều sự phụ thuộc, phát hành một phiên bản mới có thể nhanh chóng trở thành một cơn ác mộng. Nếu các thông số kỹ thuật phụ thuộc quá chặt chẽ với nhau, bạn đang ở trong sự nguy
`sự linh tinh phiên bản`
=> `sự lộn xộn của phiên bản`

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +Trong các hệ thống có nhiều sự phụ thuộc, phát hành một phiên bản mới có thể nhanh chóng trở thành một cơn ác mộng. Nếu các thông số kỹ thuật phụ thuộc quá chặt chẽ với nhau, bạn đang ở trong sự nguy
`an toàn chuyển tiếp dự án của mình` => `chuyển tiếp dự án của mình một cách an toàn`

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +Như là một giải pháp cho vấn đề này, tôi đề xuất một cách đơn giản để thiết lập các quy tắc và yêu cầu để làm thế nào gán và tăng dần các số phiên bản. Những quy tắc này là nền nhưng nó thực sự không
`Quan trọng là API phải rõ ràng và chính xác. Một khi bạn xác định API công khai của mình, bạn giao tiếp các sự thay đổi đến nó với các gia số cụ thể của mình` - seem so weird with Vietnamese.

2020-06-17 07:11 UTC, reishou commented on lang/vi/spec/v2.0.0.md
> +2. Một chữ số phiên bản bình thường PHẢI lấy từ mẫu X.Y.Z. X, Y và Z là một số nguyên không âm, và không chứa số 0 ở chữ cái đầu tiên. X là phiên bản chính, Y là phiên bản nhỏ và Z là phiên bản vá lỗ
`và không chứa số 0 ở chữ cái đầu tiên` => `và không bắt đầu bằng số 0 nếu có hai chữ số trở lên`

2020-06-17 08:45 UTC, alexandrtovmach commented
@reishou I'm apologize, but this PR already merged 😞 Would you create a new one with proposed changes?

2022-11-17 07:12 UTC, ntk148v commented
Hi folks, I've proposed changes in Vietnamese translation.

https://github.com/semver/semver.org/pull/391