docs: improve doc
semver/semver.org pull request #292
Opened 2020-09-23 18:27 UTC by apteles

2020-10-13 10:24 UTC, alexandrtovmach commented
@apteles Thank you for contribution! For translations content we require to have at least one native speaker review. Could you assign someone to handle that?

2020-10-13 13:01 UTC, apteles commented
You're welcome @alexandrtovmach . Of course I can. But I don't know how I could do that. Can you help me with any orientation?

2020-10-13 15:20 UTC, alexandrtovmach commented
Just use `@mention` to ping native speaker

2020-10-13 15:22 UTC, alexandrtovmach commented
@rogeriopradoj @walkeralencar could you help?

2020-10-19 00:22 UTC, walkeralencar requested changes
Tem uma regra de escrever o arquivo com 80 colunas, como foi feito no arquivo abaixo:
Fazendo este ajuste, estará em conformidade.

https://raw.githubusercontent.com/semver/semver.org/gh-pages/spec/v2.0.0.md

2020-10-21 03:48 UTC, walkeralencar commented
> @rogeriopradoj @walkeralencar could you help?

In terms of translation, it's OK, but need to adjust the line limit to 80 cols to maintain code compatibility.

2020-10-22 00:18 UTC, apteles commented
That's fine. Anyway the project has a lint related to style guide and it has passed. The translate it's ok like @walkeralencar said. What you think about it, @alexandrtovmach ?

2020-10-22 11:14 UTC, alexandrtovmach commented
/check

2020-10-23 17:14 UTC, walkeralencar approved these changes
based on this comment: https://github.com/semver/semver.org/pull/292#issuecomment-714040770. It's approved.

2020-10-23 17:14 UTC, walkeralencar commented on lang/pt-BR/index.md
> +        Exemplo: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.
Need to respect the line limit of 80 cols.

2020-10-23 20:32 UTC, alexandrtovmach commented
@walkeralencar Thanks for paying attention, but we're not support any length limitation anymore. It's turned off here: https://github.com/semver/semver.org/blob/gh-pages/.remarkrc#L8

2020-10-23 20:32 UTC, merged

2020-10-23 20:33 UTC, alexandrtovmach commented
@apteles Thank you for contribution 🥇 and @walkeralencar for review 👍 
You're best!