update Brazilian Portuguese translation
semver/semver.org pull request #384
Opened 2022-09-06 20:25 UTC by allima

update Brazilian Portuguese translation

- adjustment in the numbering of item 11
- inclusion of an excerpt from Backus–Naur grammar
- inclusion of questions in the FAQ and link to the semver regex example

2022-09-07 13:09 UTC, JohnTitor commented
This is for pt-BR translations, @apteles @walkeralencar could y'all review this? Thanks!

2022-09-07 13:10 UTC, JohnTitor commented on lang/pt-BR/index.md
> +
This is an unnecessary change, please drop.

2022-09-08 07:43 UTC, walkeralencar commented
> This is for pt-BR translations, @apteles @walkeralencar could y'all review this? Thanks!

Hi @JohnTitor, I will review

2022-12-10 23:59 UTC, JohnTitor commented
Friendly-ping @walkeralencar, do you have time to review this?

2022-12-13 04:40 UTC, walkeralencar requested changes
Have some issues to adjust.

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +de versão e a forma como eles mudam, transmite o significado do código
Transmitem deve ser mantido, pois está se falando de numeros de versão e como **eles** mudam.

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +2. Um número de versão normal DEVE ter o formato de X.Y.Z, onde X, Y, e Z são
Na documentação é utilizado sempre o 1. para caso seja incluido um paragrafo no meio, não seja necessário reescrever todos os demais numeros abaixo, sendo assim, a forma do _1._ no markdown deve ser mantida, já que o mesmo é interpretado adequadamente e a numeração é sequenciada no modo de visualização.

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +3. Uma vez que um pacote versionado foi lançado (released), o conteúdo desta
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +4. No início do desenvolvimento, a versão Maior DEVE ser zero (0.y.z). Qualquer
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +5. Versão 1.0.0 define a API como pública. A maneira como o número de versão é
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +6. Versão de Correção Z (x.y.Z | x > 0) DEVE ser incrementado apenas se mantiver
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +7. Versão Menor Y (x.Y.z | x > 0) DEVE  ser incrementada se uma funcionalidade
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +8. Versão Maior X (X.y.z | X > 0) DEVE ser incrementada se forem introduzidas
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +9. Uma versão de Pré-Lançamento (pre-release) PODE ser identificada adicionando
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +10. Metadados de construção (Build) DEVEM ser identificadas por adicionar um
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +11. A precedência refere-se a como as versões são comparadas entre si quando solicitadas.
mesma regra do **2.**

2022-12-13 04:40 UTC, walkeralencar commented on lang/pt-BR/index.md
> +    1. A precedência DEVE ser calculada separando a versão em identificadores Maior (major), Menor(minor), Correção (patch) e de pré-lançamento nessa ordem (os metadados de compilação não têm precedê
As linhas foram definidas com largura máxima de 80 caracteres.
Ex.: https://raw.githubusercontent.com/semver/semver.org/gh-pages/index.md

ps.: eu tb nao gosto, mas foi o padrao definido

2022-12-13 04:50 UTC, walkeralencar requested changes

2022-12-13 04:50 UTC, walkeralencar commented on lang/pt-BR/index.md
> +Essas regras são baseadas em, mas não necessariamente limitadas às, bem
Vírgula pode ser removida, para não interromper a compreensão da leitura.

2022-12-13 04:50 UTC, walkeralencar commented on lang/pt-BR/spec/v2.0.0.md
> +
as Revisões aplicadas ao index.md tb se aplicam ao v2.0.0

2026-06-12 09:58 UTC, pachecocordovamoiseseduardo-byte approved these changes

2026-06-14 01:30 UTC, JohnTitor commented
Closing in favor of https://github.com/semver/semver.org/pull/430

2026-06-14 01:30 UTC, closed without merging