Adding more PT-BR translations and fix existing translations
semver/semver.org pull request #430
Opened 2023-09-11 22:56 UTC by jlucfarias

## PR Checklist

- [x] This PR doesn't modify the files in the `spec` dir.
- [x] This PR passes `npm run lint`.
- [ ] (Optional) If you're willing to help reviews about your language's translations, add your name to the `TRANSLATORS.md`.

This PR supercede #384 and fixes #425

2023-11-14 10:07 UTC, JohnTitor commented
@LucasHT22 Could you review this when you have time? Thanks in advance!

2023-11-14 16:26 UTC, LucasHT22 requested changes
Great translation @jlucfarias ! I left some comments, if you disagree with anything, please, let me know.

2023-11-14 16:26 UTC, LucasHT22 commented on lang/pt-BR/spec/v1.0.0-beta.md
> +1. A pre-release version number MAY be denoted by appending an arbitrary
From here below it is not translated, since you translated the beginning, I suggest translating the rest too:)

2023-11-14 16:26 UTC, LucasHT22 commented on lang/pt-BR/spec/v1.0.0.md
> +
I don't see any reason to have translation specifications/translators names here, it already exists in https://semver.org/lang/pt-BR/#sobre , would make it confusing when adding new names

2023-11-14 16:26 UTC, LucasHT22 commented on lang/pt-BR/spec/v1.0.0.md
> +
Applies to other files too

2023-11-23 04:32 UTC, JohnTitor commented
@jlucfarias Could you check the above review comments? Thanks!

2023-12-02 20:33 UTC, jlucfarias commented on lang/pt-BR/spec/v1.0.0-beta.md
> +1. A pre-release version number MAY be denoted by appending an arbitrary
:man_facepalming: sorry for that

2023-12-02 20:37 UTC, jlucfarias commented
Suggestions applied now, sorry for the late response

2023-12-03 03:10 UTC, LucasHT22 approved these changes
Looks good to me:)

2023-12-03 03:12 UTC, JohnTitor approved these changes
Thank you both for contributing and reviewing!

2023-12-03 03:12 UTC, merged